package cz.timetracker.dto.mapper;

import cz.timetracker.dto.WorkLogDTO;
import cz.timetracker.entity.WorkLogEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Mapper interface responsible for converting between
 * {@link WorkLogEntity} and {@link WorkLogDTO}.
 *
 * <p>This mapper uses MapStruct to generate the implementation
 * automatically at compile time.</p>
 *
 * <p><b>Note:</b>
 * MapStruct generates the actual mapping class during compilation,
 * so we only define method signatures and mapping rules here.</p>
 */
@Mapper(componentModel = "spring")
public interface WorkLogMapper {

    /**
     * Converts a {@link WorkLogEntity} to {@link WorkLogDTO}.
     *
     * <p>If field names match, MapStruct maps them automatically.</p>
     *
     * @param source entity loaded from the database
     * @return mapped DTO used in API responses
     */
    WorkLogDTO toDTO (WorkLogEntity source);

    /**
     * Converts a {@link WorkLogDTO} to {@link WorkLogEntity}.
     *
     * <p>Custom mapping rules:</p>
     * <ul>
     *     <li>{@code id} is ignored because it is usually generated by the database.</li>
     *     <li>{@code activated} is always set to {@code true} when creating a new entity.</li>
     * </ul>
     *
     * <p><b>Note:</b>
     * We ignore the ID to prevent accidentally overwriting existing
     * database records when creating new entities.</p>
     *
     * @param source DTO coming from the client
     * @return mapped entity ready for persistence
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "activated", constant = "true")
    WorkLogEntity toEntity(WorkLogDTO source);

}
