package cz.timetracker.entity;

import cz.timetracker.entity.enums.TimerType;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity representing a single Timer.
 *
 * <p>A Timer belongs to one WorkLog and represents a time interval
 * between start and stop. It stores:
 *
 * <ul>
 *     <li>Start timestamp</li>
 *     <li>Stop timestamp</li>
 *     <li>Calculated duration in seconds</li>
 * </ul>
 *
 * <p>This class is mapped to a database table using JPA annotations.
 * It does NOT contain business logic (duration calculation should be handled in the service layer).
 */
@Entity
@Getter
@Setter
public class TimerEntity {

    /**
     * Primary key of the timer.
     *
     * <p>Automatically generated by the database.
     */
    @Id
    @SequenceGenerator(sequenceName = "timer_seq", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    /**
     * Timestamp when the timer was started.
     *
     * <p>Usually set when user presses "Start".
     */
    @Column(nullable = false)
    private LocalDateTime startedAt;

    /**
     * Timestamp when the timer was stopped.
     *
     * <p>Can be null if the timer is still running.
     */
    @Column
    private LocalDateTime stoppedAt;

    /**
     * Duration of the timer in seconds.
     *
     * <p>This value is typically calculated when the timer is stopped.
     * Keeping duration stored improves performance (no need to calculate repeatedly).
     */
    @Column
    private Long durationInSeconds;


    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TimerType status;

    @Column
    private String note;

    /**
     * Many-to-One relationship:
     * Many timers can belong to one WorkLog.
     *
     * <p>This creates a foreign key column (worklog_id) in the timers table.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "work_log_id")
    private WorkLogEntity workLog;

}
